baseURL = "https://saususge.github.io/"
languageCode = "ko-kr"
title = "Saususge's Dev Blog"
theme = "PaperMod"


[params]

  [params.profileMode]
    enabled = true
    title = "Saususge"
    subtitle = "그래픽스 프로그래머를 꿈꾸며"
    imageUrl = "images/profile.avif"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Saususge"
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "About"
      url = "/about"


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/saususge" # 본인 GitHub 프로필 링크
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/cwk95/" 
  defaultTheme = "auto"


[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[markup.highlight]
  # codeFences = true
  # guessSyntax = true
  # lineNos = true
  style = "dracula"
